language: go
sudo: false
go:
- 1.5
install:
- export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
- export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH
script:
- script/validate-dco
- script/validate-gofmt
- go test -v -short ./...
- script/generate-coverage report
